test28

diff --git a/.github/workflows/deploy_dev.yml b/.github/workflows/deploy_dev.yml
--- a/.github/workflows/deploy_dev.yml
+++ b/.github/workflows/deploy_dev.yml
@@ -179,11 +179,11 @@ jobs:
           # Set correct permissions for known_hosts
           chmod 644 ~/.ssh/known_hosts
           
-          # Test SSH connection
-          # if ! ssh -o ConnectTimeout=5 -o StrictHostKeyChecking=accept-new -i ~/.ssh/id_rsa "$DO_USERNAME@$DO_HOST" echo "SSH connection successful"; then
-          #   echo "ERROR: SSH connection test failed"
-          #   exit 1
-          # fi
+          Test SSH connection
+          if ! ssh -o ConnectTimeout=5 -o StrictHostKeyChecking=accept-new -i ~/.ssh/id_rsa "$DO_USERNAME@$DO_HOST" echo "SSH connection successful"; then
+            echo "ERROR: SSH connection test failed"
+            exit 1
+          fi
 
 
       # - name: Copy deployment files
